<?php
/*
 * Generated configuration file
 * Generated by: phpMyAdmin 4.3.8 setup script
 * Date: Sun, 29 Mar 2015 14:35:06 +0000
 */

/* Servers configuration */
$i = 0;

/* Server: docker local [1] */
$i++;
$cfg['Servers'][$i]['verbose'] = 'mysql';
$cfg['Servers'][$i]['host'] = 'mysql';
$cfg['Servers'][$i]['port'] = '';
$cfg['Servers'][$i]['socket'] = '';
$cfg['Servers'][$i]['connect_type'] = 'tcp';
$cfg['Servers'][$i]['auth_type'] = 'cookie';
$cfg['Servers'][$i]['user'] = '';
$cfg['Servers'][$i]['password'] = '';

/* End of servers configuration */

$cfg['blowfish_secret'] = 'NO_SECRET';
$cfg['DefaultLang'] = 'en';
$cfg['ServerDefault'] = 1;
$cfg['UploadDir'] = '';
$cfg['SaveDir'] = '';
$cfg['ExecTimeLimit'] = $_ENV['PHP_MAX_EXECUTION_TIME'];
?>
